[package]
name = "vocksel/tag"
description = "Module loader class that bypasses Roblox's require cache"
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = [
    "src",
    "src/**",
    "default.project.json",
    "LICENSE",
    "README.md",
    "wally.toml",
]

[dependencies]
t = "osyrisrblx/t@3.0.0"
TestEZ = "roblox/testez@0.4.1"